// src/services/twilio.js  🌟 NEW
// Delivery Engine — sends Guardian Triage Briefs via WhatsApp or SMS.
// Gracefully degrades to console mock if Twilio creds are not set
// (safe for demo environments without a paid Twilio account).

import twilio from 'twilio';

// ── Client factory (lazy, so missing keys don't crash the server) ──────────
let _client = null;
const getClient = () => {
  if (_client) return _client;
  const sid   = process.env.TWILIO_ACCOUNT_SID;
  const token = process.env.TWILIO_AUTH_TOKEN;
  if (!sid || !token) return null;  // graceful degradation
  _client = twilio(sid, token);
  return _client;
};

// ── Format the medical brief into a clean WhatsApp message ────────────────
const formatWhatsAppMessage = (brief, userName) => {
  const riskEmoji = {
    'watch':          '🟡',
    'pre-burnout':    '🟠',
    'acute-distress': '🔴',
  }[brief.risk_level] || '🟡';

  return [
    `*🧠 AURA CLINICAL ADVISORY*`,
    `*Patient:* ${userName || 'Your child'} | *${new Date().toLocaleString('en-IN', { dateStyle: 'short', timeStyle: 'short' })}*`,
    `*Risk Level:* ${riskEmoji} ${brief.risk_level.replace('-', ' ').toUpperCase()}`,
    '',
    `*📊 Detection*`,
    brief.observed_pattern,
    '',
    `*🎭 Analogy*`,
    `_"${brief.analogy}"_`,
    '',
    `*🎙️ Vocal Analysis*`,
    brief.vocal_analysis,
    '',
    `*⚙️ Aura Action Taken*`,
    brief.aura_action_taken,
    '',
    `*👋 Your Action Right Now*`,
    brief.parent_action,
    '',
    `_This message was generated by AuraOS Clinical Triage. Do not share patient data externally._`,
  ].join('\n');
};

// ── Format for SMS (shorter, no markdown) ─────────────────────────────────
const formatSmsMessage = (brief, userName) => {
  return [
    `AURA ALERT [${brief.risk_level.toUpperCase()}]`,
    `Patient: ${userName || 'your child'}`,
    `Pattern: ${brief.observed_pattern.slice(0, 120)}`,
    `Action: ${brief.parent_action.slice(0, 200)}`,
    `Sent by AuraOS.`,
  ].join(' | ');
};

// ── Main export ────────────────────────────────────────────────────────────
/**
 * Sends a Guardian Triage Brief to the configured channel.
 * Returns { success, channel, sid, mock } — never throws (safe for use in alert pipeline).
 */
export const sendGuardianAlert = async ({ brief, userName, guardianPhone, channel = 'whatsapp' }) => {
  const client = getClient();
  const from   = process.env.TWILIO_WHATSAPP_FROM || 'whatsapp:+14155238886'; // Twilio sandbox default
  const to     = guardianPhone;

  if (!to) {
    console.warn('[Twilio] No guardian phone — logging to console only.');
    console.log('[MOCK ALERT]\n', formatWhatsAppMessage(brief, userName));
    return { success: true, channel: 'mock', mock: true };
  }

  if (!client) {
    // No Twilio creds — mock delivery for demo
    console.log('[Twilio MOCK] Would send to:', to);
    console.log('[MOCK BRIEF]\n', formatWhatsAppMessage(brief, userName));
    return { success: true, channel: 'mock', mock: true };
  }

  try {
    let message;
    if (channel === 'whatsapp') {
      message = await client.messages.create({
        from: from.startsWith('whatsapp:') ? from : `whatsapp:${from}`,
        to:   to.startsWith('whatsapp:')   ? to   : `whatsapp:${to}`,
        body: formatWhatsAppMessage(brief, userName),
      });
    } else if (channel === 'sms') {
      message = await client.messages.create({
        from: process.env.TWILIO_SMS_FROM || from.replace('whatsapp:', ''),
        to,
        body: formatSmsMessage(brief, userName),
      });
    } else {
      throw new Error(`Unsupported channel: ${channel}`);
    }

    console.log(`[Twilio] Alert sent. SID: ${message.sid}`);
    return { success: true, channel, sid: message.sid, mock: false };
  } catch (err) {
    console.error('[Twilio] Send failed:', err.message);
    return { success: false, channel, error: err.message, mock: false };
  }
};