import { useState } from 'react';
import { motion } from 'framer-motion';
import { Link, useNavigate } from 'react-router-dom';
import { Link as LinkIcon, ShieldCheck } from 'lucide-react';
import { authApi } from '../../services/authApi.js';

export default function GuardianLink() {
  const navigate = useNavigate();
  const [inviteCode, setInviteCode] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);

  const handleLink = async (e) => {
    e.preventDefault();
    setBusy(true); setError(null);
    try {
      const res = await authApi.linkPatient(inviteCode);
      if (res.patient?.intakeRequired) {
        navigate(`/guardian/patient/${res.patient.id}/intake`);
      } else {
        navigate('/guardian/dashboard');
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="min-h-dvh bg-[#020915] text-[var(--text-1)] flex items-center justify-center p-4">
      <div className="absolute inset-0 pointer-events-none bg-[radial-gradient(ellipse_at_top,rgba(124,58,237,0.18),transparent_55%)]" />
      <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="relative w-full max-w-xl glass p-5 sm:p-7 rounded-lg">
        <div className="flex items-center justify-between mb-5">
          <Link to="/guardian/login" className="text-xs text-[var(--text-3)] hover:text-[#7c3aed]">Back to Login</Link>
          <span className="badge" style={{ backgroundColor: 'rgba(124,58,237,0.2)', color: '#c4b5fd' }}>
            <ShieldCheck size={12} /> Link Patient
          </span>
        </div>

        <form onSubmit={handleLink}>
          <h1 className="section-title text-[#c4b5fd]">Link a Patient</h1>
          <p className="section-sub mb-6">Enter the 24-hour invite code generated by the patient to link them to your Guardian account.</p>
          
          <div className="space-y-4">
            <input 
              className="input uppercase tracking-[0.1em]" 
              placeholder="XXXX-XXXX" 
              value={inviteCode} 
              onChange={(e) => setInviteCode(e.target.value)} 
              required 
            />
          </div>
          
          {error && <p className="mt-4 text-sm text-[#ff6b8a]">{error}</p>}
          
          <button disabled={busy || !inviteCode.trim()} className="btn w-full mt-6 flex justify-center items-center gap-2" style={{ backgroundColor: '#7c3aed', color: 'white' }}>
            {busy ? 'Linking...' : <><LinkIcon size={16} /> Link Patient</>}
          </button>
        </form>

        <button onClick={() => navigate('/guardian/dashboard')} className="btn btn-ghost w-full mt-4">Go to Dashboard Without Linking</button>
      </motion.div>
    </div>
  );
}
